>>SOURCE FORMAT FREE
IDENTIFICATION DIVISION.
PROGRAM-ID. CobReport.

ENVIRONMENT DIVISION.
INPUT-OUTPUT SECTION.
FILE-CONTROL.
  SELECT Sales-File ASSIGN TO "Sales.dat"
    ORGANISATION LINE SEQUENTIAL
    ACCESS SEQUENTIAL.

  SELECT Report-File ASSIGN TO "SalesReport.txt"
    ORGANISATION SEQUENTIAL
    ACCESS SEQUENTIAL.

PROCEDURE DIVISION.
  DISPLAY "CobReport v0.0.1".
  STOP RUN.

END PROGRAM CobReport.
