>>SOURCE FORMAT FREE
IDENTIFICATION DIVISION.
PROGRAM-ID. CobReport.

ENVIRONMENT DIVISION.
INPUT-OUTPUT SECTION.
FILE-CONTROL.
  *> Input data file
  SELECT Sales-File ASSIGN TO "Sales.dat"
    ORGANISATION LINE SEQUENTIAL
    ACCESS SEQUENTIAL.

  *> Output report file
  SELECT Report-File ASSIGN TO "SalesReport.txt"
    ORGANISATION SEQUENTIAL
    ACCESS SEQUENTIAL.

DATA DIVISION.
FILE SECTION.
  FD Sales-File.
    01 Sales-Record.
      05 FL-Sale-Num PIC 9(5).
      05 FILLER PIC X(4) VALUE ALL SPACES.
      05 FL-Profit PIC $$,$$$,$$$.99.
      05 FILLER PIC X(4) VALUE ALL SPACES.
      05 FL-Item-Sold PIC X(25).

PROCEDURE DIVISION.
  DISPLAY "CobReport v0.0.1".
  STOP RUN.

END PROGRAM CobReport.
